language: node_js

node_js:
- 0.12
- "iojs-v3.0.0"

env:
  # travis encrypt FREY_AWS_ACCESS_KEY=xyz
  - secure: "RnpXNpU4fIEt/uW8r6ljNIGeb91PDCvgdqBmjEiUscNNDfiADb/Nms3LHG9VwrHWrDX4tX9xbvxGHGGb68E2UVMykitg3bpf4GhxHxl0Z1X47CWw8b+TYtohTeZYIscAmvSaL9gCxdkh+74clwLkHxTzUrhf3yXF/1dnbWhlIoDzPEnqECvBNgHnCRtr31IB5t26ZX8iJxXOppxjrF5LWDpkAmt/+9EFVYJEY/e4EEaum/mKcNh/wcVe3fCbSqxDx4WpyPUhdhGa9/GOb6dZUS8GAMMva5W7KNtL8SPfrXnfOIxVFYQMnzocwhuwMskboDWzhYBG4u+gydizToqWJWnI1QZqW81XQJL7qRXyst6a6H/+2Aa8j48bGJTXfwELjNcp6iUEZ1V6fo9UdswzGY8a5vDs2nDmnEdcplA1gLTAGnikeOU6hudlxpbirBXlSRfiG81Q62wUYwCEaJcJdHqiirhEYdQpYUpOXaN/cfdKoiPC8avprR7SkSHf0dgV7njiU7Mk2nU+0CxoafTHTxRl+SX/6Dga1Zbp/ycQ4PebojMDZTnYArJQw18GrWHAIfr7Xi+vtNoNWXLvDOdnYFPuhb0LQ20I0LcevQ7mQodwKDfpHs4pn111Jc1wpfUKetv7cJt+c7409T3my2WC3JHaQYsqnYE0dAUGXBISpc4="
  # travis encrypt FREY_AWS_SECRET_KEY=xyz
  - secure: "b3UFzgAp40HIAxXTNeqz1UYdNL+Hg6VhJBeErSOji9Ed051d4NxUYEqJ5TXV8XDg0LfkWT4D8YwCRbZvfNBQjMUeYfaoh+n5DShhb8tHHz/7/JFgISl+cTKscC0DaOblRzWQl3fYHGRwUAtkfHCmSfQ6quDSoXZkwG6WVndYn4rQAS8fAc8kgFgaNR7KUVfYPzKdaFZ4b+qyziLO65Asx2507KeEnAIIjoF70WxfBSZvhUi4JtHZJP4J4oURytZG5Mg+trX65rRsasJ+rdvKmmFdPKXdCEFOSObE5+B6oOnHSDRwtSdvR9xGpf7STX9h3+Z/p1hrWnJPpKVDbIIy/q1FTer4oOUrCZLNRBb0f8udBwO5OEsuwVURIg0j5AYty7Q+FTLPq7lClzg8VWwhiRbDzVUsneXqVguIr4EkPjNNEJqLBdAEFVWFFeEejZ/gNRZ6766gogVYmmCggaBaTlvAAOooycMbBJpUon45jkZktbm83QFMa9L6t7nF4IYlCWoYCNt2YS+Oz63KjjP+XejwvBD7rBeRsp6JFDBS+elCq57XTw6aZ4K5qmRklopFKnzpcL+JLST9dX6XmHihWQM1KRUb9QZBreycwr7fRVmD740bm1X4NcaE1omno43GiYTWesYPR01yzLHDdzcrzMRPDI26lnq3NzezyINSglU="

matrix:
  allow_failures:
  - node_js: "iojs-v3.0.0"

script: make test-full
