sudo: required
language: node_js
node_js:
- 4.2.1
env:
  global:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - realpath
cache:
  apt: true
  directories:
  - node_modules
notications:
  slack:
    secure: HdV6fSf3MPmwpseMdPzs/wXWTpn/6/mUhV0uI12WiASnQj2lcsMZLrOfFJSdBVAroACLVs6vC7GEzV7Dz8aimkXHvL2qN5Djc+9Pz4DLWwRLULndjjmQhkCfYEQiA9Pzy9h95PfvfnACTEtD7BWdkZddSppwc7VPmvj7AuuW0CeJNGAdnnqtf3w2eHsKdSQSDcEEorrWniBBTVIVKpQ0Wwl1dVh0bjTVVXDc7t0mNHepi6hrJH4qyhKwY8YTVXc11gZvktXsTWM+YOokyxAKPNNE/eYHC1V/AR29LjLSlA9pO/wZfVam/UomLAMbZdEBa7OBfnHrhOOsYrJPVoP7T71p2FJUKAopb/0+L1oSVas+DZScdXuKssnkoAa+A6a4Eh7fAMqqHx3J1O4mQCrvwaCu/CkjuCM6NMoPUYqRplel5Zaj39TxDLZhMWhGjNPkhqTkFZZ237ZCGfSbr3aXk6NrpNLXvBMRMbJfFxd2+2Qftrx+HCeAIlQGT5BIUO/q65hc0Lsfiwff7GEisZTYsKUlfstj3ozgOC04UQwdgnYFwDHWlA9dPK4dNWyaQ86/Z4RWGkn/64u40H9RVjyGb0CUGb5zDbb5egnYJ475uJ3wybDE9zuTm8KOQ5NsfE/Pbbpq/MxIcdhExRj4CA5ToUO8u+P83H7WjVhkyiUMnSw=
before_install:
- pip install --user pyhcl==0.1.15
- wget https://github.com/dbohdan/remarshal/releases/download/v0.3.0/remarshal-0.3.0-linux-amd64.tar.gz
- tar -zxvf remarshal-0.3.0-linux-amd64.tar.gz
- mkdir ~/bin
- export PATH="~/bin:${PATH}"
- cp -af remarshal/remarshal ~/bin/remarshal
script: npm run test:full
