language: node_js

sudo: required

node_js:
- 0.12
- "iojs-v3.0.0"

env:
  global:
    # source env.sh && travis encrypt FREY_AWS_ACCESS_KEY=${FREY_AWS_ACCESS_KEY}
    - secure: "w+8VhV3vQyqWL1fGzLIrJde9VgwijqxmdBcPLRVogs/demvh/Qop30BToGaJ2G01jQXRAzN8pMVF7LBArFbiPY70qBWKU8zhjOfNWaG8oQ/rh+XFheh2yCN48MxilkUMj5bZJZKlJ+l6DDj6onjTroxi9TR2CLR94BLKeObZEoTPPdhQmjNifXvAWlko+8TokC3xDa0ixIUr8Au/gQAN7xulfEjGTdywQORq+/Vrc4sbEgvD5OLpEEXxYDL0LYL+kAag4z5C7PtRKvZcyzic6S/p9vf4hnrwki8VM0z52K2lPS+vThb+X/36RYMSYXymUg/mvcqt7x2MRFNUCiS8vtTw1WYEx5MSEfGPE7nBectIjVqkHrMVck5rbHzIyuErq7LLf08IKylwpmuivVG6g2mGReoZYr2e301dvGqr44pI4PQo7N2dwRXSVy8CK9yNYN/LuK7iBxFxRsJscuVgB+AdJ2HVeXF5/4IjxGnZXYmWY4Ft3ndrLTPgUkiCSPbcfsGJ70DNoJSQEfTXifNBk8PCUxg7OfiTgmsi8lirMUyhlJ2vwbAKBB+I+gZrIYw4XmEu9AfES+kGkVEPjjzMQOHnGfpRSZiw4MZ2/CgciLQjn5Xcx6vfTL5yNdh7PCSmqj5HMjcSWPYVaZ4jcxDJAJJlyi6vQaMEo1THbhJc74I="
    # source env.sh && travis encrypt FREY_AWS_SECRET_KEY=${FREY_AWS_SECRET_KEY}
    - secure: "atZlSO+vfPN30SqECqQQDkXCvCKQ2l3RpLqWxLrTwY070308kgAV9d/Wdc0RaZvmLHsmCYxkn2QudqYNJtoQ0d0cfz2dgapLfSo1lXSiqqMQcXr2KjEPnYGvVhzCf9YyZ4lCikcfhthX9Z2K9tZ67KNqpKxsHYIAEUcCKy4ycPiZKaVc4ke05NqtkKcJdxiWeYIckax8LIg2fJFiJxpeMw77GeKmi1DAb3hgj3GY75N+9anaiaRjIh6PdpqG+0icXpvclR8gyOd54oDn7ZLxeCBowrl8RO5KIqkgQt6yqK18t2x/vs2RNMen6Q/voIpTYh2eMMuNYNTGUQoIiQyqQWBxQBxVOe6mEEchhywBZl0W5U3Q474+8T+N2Pb/LAWJ5am5l9OMBoge8ztF4rjwe54OLV3mjGKBtIcnM5d6FNTIa5gUiJfcJEvQUYRyE9JLhmRIBXKETSarK7ArQWqj30PGNCuIAuj48lJzEUQ5SxniNJVgT6Nnoy/Al2psxzdy2VIGemT6iBBsDG/6V8R1RMa7YWAxz1vAkvKz5Yd60orctTvZ6YXv05QFTutqXNyu3WdEObJyF99xB5gqSisvv0xoJS+AOWbE/HAO6JHdSllW094O3sUkDSYCEhKyV6BpcxaCBtPTOdEN/6qfAHcB9iCUFP0xyrL2rXD09oDuqAA="

notications:
  slack:
    # travis encrypt "transloadit:xyzabc"
    secure: "HdV6fSf3MPmwpseMdPzs/wXWTpn/6/mUhV0uI12WiASnQj2lcsMZLrOfFJSdBVAroACLVs6vC7GEzV7Dz8aimkXHvL2qN5Djc+9Pz4DLWwRLULndjjmQhkCfYEQiA9Pzy9h95PfvfnACTEtD7BWdkZddSppwc7VPmvj7AuuW0CeJNGAdnnqtf3w2eHsKdSQSDcEEorrWniBBTVIVKpQ0Wwl1dVh0bjTVVXDc7t0mNHepi6hrJH4qyhKwY8YTVXc11gZvktXsTWM+YOokyxAKPNNE/eYHC1V/AR29LjLSlA9pO/wZfVam/UomLAMbZdEBa7OBfnHrhOOsYrJPVoP7T71p2FJUKAopb/0+L1oSVas+DZScdXuKssnkoAa+A6a4Eh7fAMqqHx3J1O4mQCrvwaCu/CkjuCM6NMoPUYqRplel5Zaj39TxDLZhMWhGjNPkhqTkFZZ237ZCGfSbr3aXk6NrpNLXvBMRMbJfFxd2+2Qftrx+HCeAIlQGT5BIUO/q65hc0Lsfiwff7GEisZTYsKUlfstj3ozgOC04UQwdgnYFwDHWlA9dPK4dNWyaQ86/Z4RWGkn/64u40H9RVjyGb0CUGb5zDbb5egnYJ475uJ3wybDE9zuTm8KOQ5NsfE/Pbbpq/MxIcdhExRj4CA5ToUO8u+P83H7WjVhkyiUMnSw="

matrix:
  allow_failures:
  - node_js: "iojs-v3.0.0"

install:
  - pip install --user pyhcl
  - wget https://github.com/dbohdan/remarshal/releases/download/v0.3.0/remarshal-0.3.0-linux-amd64.tar.gz
  - tar -zxvf remarshal-0.3.0-linux-amd64.tar.gz

script: make test-full
