---
# Performs symlink exchange
- name: ANSISTRANO | Change softlink to new release
  file: state=link path={{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }} src=./{{ ansistrano_version_dir }}/{{ ansistrano_release_version }}
