# meta file for rsyslog
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Manage rsyslog and rsyslog.d in Debian-like systems
  license: MIT
  min_ansible_version: 1.9.6
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - monitoring
dependencies: []
